xcodeproj 'RollingPaper.xcodeproj'
platform :ios, '5.1'

pod 'AFNetworking', 	   '~> 1.3.0'
pod 'Facebook-iOS-SDK',    '~> 3.5.1'
pod 'SYCache'
pod 'JSONKit'
pod 'MBProgressHUD'
pod 'Underscore.m'

target :Specs do
  pod 'Cedar'
  pod 'OCMock'
end