xcodeproj 'RollingPaper.xcodeproj'
platform :ios, '6.0'

pod 'AFNetworking', '1.3.2'
pod 'Facebook-iOS-SDK', '3.7.0'
pod 'JSONKit'
pod 'MBProgressHUD'
pod 'Underscore.m'

target :Specs do
  pod 'Cedar'
  pod 'OCMock'
end