xcodeproj 'RollingPaper.xcodeproj'
platform :ios, '5.1'

pod 'AFNetworking'
pod 'Facebook-iOS-SDK'
pod 'JSONKit'
pod 'MBProgressHUD'
pod 'Underscore.m'

target :Specs do
  pod 'Cedar'
  pod 'OCMock'
end